services:
  - type: web
    name: my-docker-web-service
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
